#!/bin/bash

# ISEB Platform - Module Installation Script
# This script installs all ISEB modules in the correct order

set -e

echo "=========================================="
echo "ISEB Platform - Module Installation"
echo "=========================================="
echo ""

# Database name
DB_NAME="iseb_prod"

# Check if Odoo is running
if ! curl -s http://localhost:8069 > /dev/null; then
    echo "ERROR: Odoo is not accessible at http://localhost:8069"
    echo "Please start Docker containers first: docker compose up -d"
    exit 1
fi

echo "✓ Odoo is running"
echo ""

echo "=========================================="
echo "Installation Order:"
echo "=========================================="
echo "1. Base Odoo modules (account, account_accountant)"
echo "2. ISEB Custom Modules:"
echo "   - french_accounting (French FEC compliance)"
echo "   - client_portal (Client web interface)"
echo "   - cabinet_portal (Accounting firm portal)"
echo "   - bank_sync (Bank synchronization)"
echo "   - e_invoicing (Electronic invoicing)"
echo "   - reporting (Custom reports)"
echo ""

echo "=========================================="
echo "IMPORTANT: Manual Installation Required"
echo "=========================================="
echo ""
echo "Please follow these steps in the Odoo web interface:"
echo ""
echo "1. Access: http://localhost:8069"
echo "   - Username: admin"
echo "   - Password: (your database password)"
echo ""
echo "2. Install Base Accounting Modules:"
echo "   Apps → Search 'Accounting' → Install"
echo "   Apps → Search 'Invoicing' → Install (if not auto-installed)"
echo ""
echo "3. Install French Localization (IMPORTANT FIRST):"
echo "   Apps → Remove 'Apps' filter"
echo "   Search: 'France - Accounting'"
echo "   Install: 'France - Accounting' module"
echo "   This will install:"
echo "   - French chart of accounts (PCG)"
echo "   - French taxes (TVA)"
echo "   - FEC compliance"
echo ""
echo "4. Configure Company:"
echo "   Settings → General Settings → Companies"
echo "   Set: Country = France"
echo "   Set: Currency = EUR"
echo "   Set: Fiscal Position = France"
echo ""
echo "5. Install ISEB Custom Modules (in order):"
echo ""
echo "   a) french_accounting"
echo "      Apps → Remove 'Apps' filter → Search 'French Accounting - ISEB'"
echo "      → Install"
echo "      Purpose: FEC export, TVA declarations"
echo ""
echo "   b) client_portal"
echo "      Apps → Search 'Client Portal - ISEB' → Install"
echo "      Purpose: Client web interface, document upload, dashboards"
echo ""
echo "   c) reporting"
echo "      Apps → Search 'Custom Reporting - ISEB' → Install"
echo "      Purpose: Custom financial reports"
echo ""
echo "   d) e_invoicing"
echo "      Apps → Search 'Electronic Invoicing - ISEB' → Install"
echo "      Purpose: Factur-X, Chorus Pro"
echo ""
echo "   e) bank_sync"
echo "      Apps → Search 'Bank Synchronization - ISEB' → Install"
echo "      Purpose: Automatic bank transaction import"
echo ""
echo "   f) cabinet_portal"
echo "      Apps → Search 'Cabinet Portal - ISEB' → Install"
echo "      Purpose: Accounting firm task management"
echo ""
echo "=========================================="
echo "Post-Installation Configuration"
echo "=========================================="
echo ""
echo "6. Create Portal Users:"
echo "   Settings → Users → Create"
echo "   - Select 'Portal' access rights"
echo "   - Link to partner/client"
echo "   - Set password and send invitation"
echo ""
echo "7. Access Client Portal:"
echo "   - Portal URL: http://localhost:8069/my"
echo "   - Login with portal user credentials"
echo ""
echo "8. Test Features:"
echo "   - Upload a document (Facture fournisseur)"
echo "   - Check dashboard"
echo "   - Test OCR (if document is PDF/image)"
echo ""
echo "=========================================="
echo "Troubleshooting"
echo "=========================================="
echo ""
echo "If module installation fails:"
echo "1. Check logs: docker compose logs odoo --tail=100"
echo "2. Restart Odoo: docker compose restart odoo"
echo "3. Update app list: Apps → Update Apps List"
echo ""
echo "If you see 'Module not found':"
echo "1. Verify addons path: Settings → Technical → System Parameters"
echo "   → Look for 'addons_path'"
echo "   → Should include: /mnt/extra-addons"
echo ""
echo "=========================================="
echo "Access URLs"
echo "=========================================="
echo ""
echo "• Backend (Admin):  http://localhost:8069"
echo "• Client Portal:    http://localhost:8069/my"
echo "• Health Check:     http://localhost:8069/web/health"
echo ""
echo "=========================================="
echo "Ready to install!"
echo "=========================================="
echo ""
echo "Open your browser to: http://localhost:8069"
echo ""
